---
title: "OCR tool to find cartridges on a shelf"
description: "I built a tool that helps me at my work"
date: 2026-08-23
---

Job search after graduating from grad school hasn't exactly gone swimmingly. I took up a part time retail job to keep the bills paid while I continued looking for jobs. I am not sure I can mention the name of the company here but it's a company that sells stationery and rhymes with "maples".

Anyway, part of my job included stocking the shelves. Basically, if something isn't on display and we had the stock, I had to move it from the storage to the display. 

For most categories, this was fine; the search itself didn't take very long because I knew where most of the stock used to be. For printer ink cartridges however, this proved to be very annoying.

The problem was that there were too many types of cartridges. HP alone has released well over 100 different cartridge model numbers. What's worse is that neither the display nor the storage was sorted by any key (neither the model number nor the SKU/UPC). So if there was a gap in display, I had to scan the 100s of boxes we had in the storage looking for the exact one. What adds to the complexity is that cartridges can also be of multiple types: standard or XL cartridges which had more ink.

For HP cartridges alone, the overhead storage spanned three different sections. So I would need to wheel the ladder to the first section, manually check each row to see if the cartridge I had was there and then move the ladder over to the next if it wasn't and resume searching. This was annoying as often times I'd miss the cartridge and I would have to wheel back the ladder to a previous section to grab it.

I thought this problem was easily solvable with some optical recognition model which is exactly what I built. I used PaddleOCR that took in a photo and return a list of every string it found with a bounding box and a confidence score. The matching takes that list and decides whether the cartridge number I was looking for exists or not. If it does, it annotates the image and sends it back. At work, I just take a photo and input the list of boxes and the type of cartridge I am looking for, and get back the annotated image. I used FastAPI on the serving path and password protected it with a signed-cookie. Frontend is just a basic HTML file. I self-hosted it using a CloudFlare tunnel because I didn't want to pay to host it on an EC2 instance.
